spring:
  application:
    name: olders-information-management-system
#数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/test-project
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#Mybatis的相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true